export const SHOPPING_ADD_PRODUCT = 'SHOPPING_ADD_PRODUCT';
export const SHOPPING_REMOVE_PRODUCT = 'SHOPPING_REMOVE_PRODUCT';
export const SHOPPING_DELIVERY_ADDRESS = 'SHOPPING_DELIVERY_ADDRESS';
export const SHOPPING_PAYPAL = 'SHOPPING_PAYPAL';
export const CART_EMPTY = 'CART_EMPTY';
