export const SHOPPING_ADD_PPT_PRODUCT = 'SHOPPING_ADD_PPT_PRODUCT';
export const SHOPPING_DELETE_PPT_PRODUCT = 'SHOPPING_DELETE_PPT_PRODUCT';
export const SHOPPING_DELIVERY_ADDRESS = 'SHOPPING_DELIVERY_ADDRESS';
export const SHOPPING_PAYPAL = 'SHOPPING_PAYPAL';
export const CART_EMPTY = 'CART_EMPTY';
