export const PURCHASE_NEW_REQUEST = 'PURCHASE_NEW_REQUEST';
export const PURCHASE_NEW_COMPLETE = 'PURCHASE_NEW_COMPLETE';
export const PURCHASE_NEW_ERROR = 'PURCHASE_NEW_ERROR';
export const ORDER_CREATE_RESET = 'ORDER_CREATE_RESET';

export const PURCHASE_PAYPAL_REQUEST = 'PURCHASE_PAYPAL_REQUEST';
export const PURCHASE_PAYPAL_COMPLETE = 'PURCHASE_PAYPAL_COMPLETE';
export const PURCHASE_PAYPAL_ERROR = 'PURCHASE_PAYPAL_ERROR';
export const ORDER_PAY_RESET = 'ORDER_PAY_RESET';

export const PURCHASE_SHIPPING_REQUEST = 'PURCHASE_SHIPPING_REQUEST';
export const PURCHASE_SHIPPING_COMPLETE = 'PURCHASE_SHIPPING_COMPLETE';
export const PURCHASE_SHIPPING_ERROR = 'PURCHASE_SHIPPING_ERROR';
export const ORDER_DELIVER_RESET = 'ORDER_DELIVER_RESET';

export const PURCHASE_INFO_REQUEST = 'PURCHASE_INFO_REQUEST';
export const PURCHASE_INFO_COMPLETE = 'PURCHASE_INFO_COMPLETE';
export const PURCHASE_INFO_ERROR = 'PURCHASE_INFO_ERROR';

export const PURCHASE_ACCOUNT_HISTORY_REQUEST = 'PURCHASE_ACCOUNT_HISTORY_REQUEST';
export const PURCHASE_ACCOUNT_HISTORY_COMPLETE = 'PURCHASE_ACCOUNT_HISTORY_COMPLETE';
export const PURCHASE_ACCOUNT_HISTORY_ERROR = 'PURCHASE_ACCOUNT_HISTORY_ERROR';

export const PURCHASE_HISTORY_REQUEST = 'PURCHASE_HISTORY_REQUEST';
export const PURCHASE_HISTORY_COMPLETE = 'PURCHASE_HISTORY_COMPLETE';
export const PURCHASE_HISTORY_ERROR = 'PURCHASE_HISTORY_ERROR';

export const PURCHASE_REMOVE_REQUEST = 'PURCHASE_REMOVE_REQUEST';
export const PURCHASE_REMOVE_COMPLETE = 'PURCHASE_REMOVE_COMPLETE';
export const PURCHASE_REMOVE_ERROR = 'PURCHASE_REMOVE_ERROR';
export const ORDER_DELETE_RESET = 'ORDER_DELETE_RESET';
