export const ITEM_HISTORY_REQUEST = 'ITEM_HISTORY_REQUEST';
export const ITEM_HISTORY_COMPLETE = 'ITEM_HISTORY_COMPLETE';
export const ITEM_HISTORY_ERROR = 'ITEM_HISTORY_ERROR';

export const ITEM_INFO_REQUEST = 'ITEM_INFO_REQUEST';
export const ITEM_INFO_COMPLETE = 'ITEM_INFO_COMPLETE';
export const ITEM_INFO_ERROR = 'ITEM_INFO_ERROR';

export const ITEM_NEW_REQUEST = 'ITEM_NEW_REQUEST';
export const ITEM_NEW_COMPLETE = 'ITEM_NEW_COMPLETE';
export const ITEM_NEW_ERROR = 'ITEM_NEW_ERROR';
export const PRODUCT_CREATE_RESET = 'PRODUCT_CREATE_RESET';

export const ITEM_REVIEW_NEW_REQUEST = 'ITEM_REVIEW_NEW_REQUEST';
export const ITEM_REVIEW_NEW_COMPLETE = 'ITEM_REVIEW_NEW_COMPLETE';
export const ITEM_REVIEW_NEW_ERROR = 'ITEM_REVIEW_NEW_ERROR';
export const PRODUCT_REVIEW_CREATE_RESET = 'PRODUCT_REVIEW_CREATE_RESET';

export const ITEM_AMMEND_REQUEST = 'ITEM_AMMEND_REQUEST';
export const ITEM_AMMEND_COMPLETE = 'ITEM_AMMEND_COMPLETE';
export const ITEM_AMMEND_ERROR = 'ITEM_AMMEND_ERROR';
export const PRODUCT_UPDATE_RESET = 'PRODUCT_UPDATE_RESET';

export const ITEM_REMOVE_REQUEST = 'ITEM_REMOVE_REQUEST';
export const ITEM_REMOVE_COMPLETE = 'ITEM_REMOVE_COMPLETE';
export const ITEM_REMOVE_ERROR = 'ITEM_REMOVE_ERROR';
export const PRODUCT_DELETE_RESET = 'PRODUCT_DELETE_RESET';

export const ITEM_CATEGORY_FILTER_REQUEST = 'ITEM_CATEGORY_FILTER_REQUEST';
export const ITEM_CATEGORY_FILTER_COMPLETE = 'ITEM_CATEGORY_FILTER_COMPLETE';
export const ITEM_CATEGORY_FILTER_ERROR = 'ITEM_CATEGORY_FILTER_ERROR';

export const ITEM_BRAND_FILTER_REQUEST = 'ITEM_BRAND_FILTER_REQUEST';
export const ITEM_BRAND_FILTER_COMPLETE = 'ITEM_BRAND_FILTER_COMPLETE';
export const ITEM_BRAND_FILTER_ERROR = 'ITEM_BRAND_FILTER_ERROR';