// Reused code from tutorials - https://github.com/basir/amazona , https://www.udemy.com/course/build-ecommerce-website-like-amazon-react-node-mongodb , https://www.youtube.com/watch?v=TRCDsB9i3bI&list=PLSV-EvELRCzBvF5d0IQGnD9m5dnvKrJ8K&index=29c
//Reused edited
export const PURCHASE_NEW_REQUEST = 'PURCHASE_NEW_REQUEST';
export const PURCHASE_NEW_COMPLETE = 'PURCHASE_NEW_COMPLETE';
export const PURCHASE_NEW_ERROR = 'PURCHASE_NEW_ERROR';
export const PURCHASE_NEW_REFRESH = 'PURCHASE_NEW_REFRESH';

export const PURCHASE_PAYPAL_REQUEST = 'PURCHASE_PAYPAL_REQUEST';
export const PURCHASE_PAYPAL_COMPLETE = 'PURCHASE_PAYPAL_COMPLETE';
export const PURCHASE_PAYPAL_ERROR = 'PURCHASE_PAYPAL_ERROR';
export const PURCHASE_PAYPAL_REFRESH = 'PURCHASE_PAYPAL_REFRESH';

export const PURCHASE_SHIPPING_REQUEST = 'PURCHASE_SHIPPING_REQUEST';
export const PURCHASE_SHIPPING_COMPLETE = 'PURCHASE_SHIPPING_COMPLETE';
export const PURCHASE_SHIPPING_ERROR = 'PURCHASE_SHIPPING_ERROR';
export const PURCHASE_SHIPPING_REFRESH = 'PURCHASE_SHIPPING_REFRESH';

export const PURCHASE_INFO_REQUEST = 'PURCHASE_INFO_REQUEST';
export const PURCHASE_INFO_COMPLETE = 'PURCHASE_INFO_COMPLETE';
export const PURCHASE_INFO_ERROR = 'PURCHASE_INFO_ERROR';

export const PURCHASE_ACCOUNT_HISTORY_REQUEST = 'PURCHASE_ACCOUNT_HISTORY_REQUEST';
export const PURCHASE_ACCOUNT_HISTORY_COMPLETE = 'PURCHASE_ACCOUNT_HISTORY_COMPLETE';
export const PURCHASE_ACCOUNT_HISTORY_ERROR = 'PURCHASE_ACCOUNT_HISTORY_ERROR';

export const PURCHASE_HISTORY_REQUEST = 'PURCHASE_HISTORY_REQUEST';
export const PURCHASE_HISTORY_COMPLETE = 'PURCHASE_HISTORY_COMPLETE';
export const PURCHASE_HISTORY_ERROR = 'PURCHASE_HISTORY_ERROR';

export const PURCHASE_REMOVE_REQUEST = 'PURCHASE_REMOVE_REQUEST';
export const PURCHASE_REMOVE_COMPLETE = 'PURCHASE_REMOVE_COMPLETE';
export const PURCHASE_REMOVE_ERROR = 'PURCHASE_REMOVE_ERROR';
export const PURCHASE_REMOVE_REFRESH = 'PURCHASE_REMOVE_REFRESH';
