const data = {
  PPTitems: [
    {
      _id: '1',
      name: 'Nike Slim Shirt',
      item_category: 'Shirts',
      picture: '/images/p1.jpg',
      cost: 120,
      stock_number: 10,
      product_brand: 'Nike',
      user_rating: 4.5,
      review_count: 10,
      item_info: 'high quality item',
    },
    {
      _id: '2',
      name: 'Adidas Fit Shirt',
      item_category: 'Shirts',
      picture: '/images/p2.jpg',
      cost: 100,
      stock_number: 20,
      product_brand: 'Adidas',
      user_rating: 4.0,
      review_count: 10,
      item_info: 'high quality item',
    },
    {
      _id: '3',
      name: 'Lacoste Free Shirt',
      item_category: 'Shirts',
      picture: '/images/p3.jpg',
      cost: 220,
      stock_number: 0,
      product_brand: 'Lacoste',
      user_rating: 4.8,
      review_count: 17,
      item_info: 'high quality item',
    },
    {
      _id: '4',
      name: 'Nike Slim Pant',
      item_category: 'Pants',
      picture: '/images/p4.jpg',
      cost: 78,
      stock_number: 15,
      product_brand: 'Nike',
      user_rating: 4.5,
      review_count: 14,
      item_info: 'high quality item',
    },
    {
      _id: '5',
      name: 'Puma Slim Pant',
      item_category: 'Pants',
      picture: '/images/p5.jpg',
      cost: 65,
      stock_number: 5,
      product_brand: 'Puma',
      user_rating: 4.5,
      review_count: 10,
      item_info: 'high quality item',
    },
    {
      _id: '6',
      name: 'Adidas Fit Pant',
      item_category: 'Pants',
      picture: '/images/p6.jpg',
      cost: 139,
      stock_number: 12,
      product_brand: 'Adidas',
      user_rating: 4.5,
      review_count: 15,
      item_info: 'high quality item',
    },
  ],
};
export default data;
