const data = {
  products: [
    {
      _id: '1',
      name: 'Nike Slim Shirt',
      productCategory: 'Shirts',
      picture: '/images/p1.jpg',
      price: 120,
      countInStock: 10,
      productBrand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      productDescription: 'high quality item',
    },
    {
      _id: '2',
      name: 'Adidas Fit Shirt',
      productCategory: 'Shirts',
      picture: '/images/p2.jpg',
      price: 100,
      countInStock: 20,
      productBrand: 'Adidas',
      rating: 4.0,
      numReviews: 10,
      productDescription: 'high quality item',
    },
    {
      _id: '3',
      name: 'Lacoste Free Shirt',
      productCategory: 'Shirts',
      picture: '/images/p3.jpg',
      price: 220,
      countInStock: 0,
      productBrand: 'Lacoste',
      rating: 4.8,
      numReviews: 17,
      productDescription: 'high quality item',
    },
    {
      _id: '4',
      name: 'Nike Slim Pant',
      productCategory: 'Pants',
      picture: '/images/p4.jpg',
      price: 78,
      countInStock: 15,
      productBrand: 'Nike',
      rating: 4.5,
      numReviews: 14,
      productDescription: 'high quality item',
    },
    {
      _id: '5',
      name: 'Puma Slim Pant',
      productCategory: 'Pants',
      picture: '/images/p5.jpg',
      price: 65,
      countInStock: 5,
      productBrand: 'Puma',
      rating: 4.5,
      numReviews: 10,
      productDescription: 'high quality item',
    },
    {
      _id: '6',
      name: 'Adidas Fit Pant',
      productCategory: 'Pants',
      picture: '/images/p6.jpg',
      price: 139,
      countInStock: 12,
      productBrand: 'Adidas',
      rating: 4.5,
      numReviews: 15,
      productDescription: 'high quality item',
    },
  ],
};
export default data;
